blank_issues_enabled: false
contact_links:
  - name: Question or idea
    url: https://github.com/markvrma/msm/issues/new?template=feature_request.yml
    about: Not sure it's a bug? Describe it as a feature request or start there.
